package com.cerproduction.dumpadosan.view;

import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Spinner;
import com.cerproduction.dumpadosan.R;
import com.cerproduction.dumpadosan.controller.InitFragment;

/**
 * @author Lazar Cerovic
 * This class handles the two spinners in the required initial form in the app.
 * Sets the items and layout of the spinners.
 */
public class SpinnerChoice implements AdapterView.OnItemSelectedListener {

    public Spinner spinner_prillor, spinner_dosor;

    /**
     * A constructor for the spinner class. Initializes the two spinners. Uses arrayadapter to
     *
     * @param v
     * @param f
     */
    public SpinnerChoice(View v, InitFragment f){

        spinner_prillor = (Spinner) v.findViewById(R.id.spinner_prillor);
        spinner_dosor = (Spinner) v.findViewById(R.id.spinner_dosor);

        ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource( f.getActivity(),
                R.array.snus_per_day, android.R.layout.simple_spinner_item);


        ArrayAdapter<CharSequence> adapter2 = ArrayAdapter.createFromResource(f.getActivity(),
                R.array.snus_per_week, android.R.layout.simple_spinner_item);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        adapter2.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner_prillor.setAdapter(adapter);
        spinner_dosor.setAdapter(adapter2);
    }

    /**
     * Autogenerated method. Currently not used
     * @param adapterView
     * @param view
     * @param i
     * @param l
     */
    @Override
    public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
    }

    /**
     * Autogenerated method. Currently not used.
     * @param adapterView
     */
    @Override
    public void onNothingSelected(AdapterView<?> adapterView) {
    }

}
