package com.cerproduction.dumpadosan.controller;

import android.content.Intent;
import android.os.Bundle;

import com.cerproduction.dumpadosan.model.Goal;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.tabs.TabLayout;

import androidx.annotation.NonNull;
import androidx.viewpager.widget.ViewPager;
import androidx.appcompat.app.AppCompatActivity;

import android.view.Menu;
import android.view.MenuItem;
import android.view.View;

import com.cerproduction.dumpadosan.view.SectionsPagerAdapter;
import com.cerproduction.dumpadosan.R;

/**
 * @author Lazar Cerovic (2020)
 * MainActivity class is the host for the two tabbed fragments. This class also holds
 * the floating action button, which is used to add goals.
 */
public class MainActivity extends AppCompatActivity {

    /**
     * Standard and autogenerated method for Activity. Initializes the Viewpager, tablayout and
     * floating action button.
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        SectionsPagerAdapter sectionsPagerAdapter = new SectionsPagerAdapter(this, getSupportFragmentManager());
        ViewPager viewPager = findViewById(R.id.view_pager);
        viewPager.setAdapter(sectionsPagerAdapter);
        TabLayout tabs = findViewById(R.id.tabs);
        tabs.setupWithViewPager(viewPager);
        FloatingActionButton fab = findViewById(R.id.fab);


        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                startActivity(new Intent(MainActivity.this, AddGoalsActivity.class));
            }
        });
    }

    /**
     * Autogenerated method for the option menu
     * @param menu
     * @return true (boolean)
     */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.settings_list, menu);
        return true;
    }

    /**
     * Returns an integer id which represents one item in the menu
     * @param item
     * @return boolean
     */
    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
        switch (item.getItemId()) {
            case R.id.item_setting:
                startActivity(new Intent(MainActivity.this, PreferencesActivity.class));
                return true;
             case R.id.item_support:
                 startActivity(new Intent(MainActivity.this, SupportActivity.class));
                return true;
            case R.id.item_about:
                startActivity(new Intent(MainActivity.this, AboutActivity.class));
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

}